let coches = {
    'coche 1': {
        marca: "Honda",
        modelo: "Civic",
        anio: 2020,
        color: "rojo",
        precio: 25000,
        carateristicas: [
            "transmision automatica",
            "techo corredizo",
            "sistema de navegacion",
        ],
        enVenta: true,
        propietario: {
        nombre: "John",
        edad: 35,
        localizacion: "New York",
        },
    },
    'coche 2': {
        marca: "Chevrolet",
        modelo: "Camaro",
        anio: 2019,
        color: "negro",
        precio: 30000,
        carateristicas: [
        "transmision manual",
        "asientos de piel",
        "sistema de sonido premium",
        ],
        enVenta: false,
        propietario: {
        nombre: "Samantha",
        edad: 28,
        localizacion: "Los Angeles",
        },
    },
    'coche 3': {
        marca: "Tesla",
        modelo: "Model S",
        anio: 2021,
        color: "plata",
        precio: 100000,
        carateristicas: [
        "motor electrico",
        "conduccion autonoma",
        "doble motor de traccion total",
        ],
        enVenta: true,
        propietario: {
        nombre: "Mike",
        edad: 40,
        localizacion: "San Francisco",
        },
    },
    'coche 4': {
        marca: "Volkswedadn",
        modelo: "Golf",
        anio: 2018,
        color: "azul",
        precio: 20000,
        carateristicas: [
        "turbocharged engine",
        "techo corredizo panoramico",
        "control de crucero adaptativo",
        ],
        enVenta: false,
        propietario: {
        nombre: "Emily",
        edad: 32,
        localizacion: "Chicago",
        },
    },
    'coche 5': {
        marca: "Toyota",
        modelo: "Corolla",
        anio: 2020,
        color: "blanco",
        precio: 22000,
        carateristicas: [
        "transmision automatica",
        "pantalla tactil",
        "camara trasera",
        ],
        enVenta: true,
        propietario: {
        nombre: "David",
        edad: 29,
        localizacion: "Houston",
        },
    },
    'coche 6': {
        marca: "",
        modelo: "Focus",
        anio: 2022,
        color: "gris",
        precio: 24000,
        carateristicas: [
        "transmision automatica",
        "pantalla tactil",
        "camara trasera",
        "monitoreo de punto ciego",
        ],
        enVenta: true,
        propietario: {
        nombre: "Alex",
        edad: 31,
        localizacion: "Seattle",
        },
    },
    'coche 7': {
        marca: "Ford",
        modelo: "Mustang",
        anio: 2020,
        color: "amarillo",
        precio: 35000,
        carateristicas: [
        "transmision manual",
        "asientos de piel",
        "sistema de sonido premium",
        "modo sport",
        ],
        enVenta: false,
        propietario: {
        nombre: "Karen",
        edad: 26,
        localizacion: "Boston",
        },
    },
    'coche 8': {
        marca: "Hyundai",
        modelo: "Tucson",
        anio: 2021,
        color: "naranja",
        precio: 30000,
        carateristicas: [
        "transmision automatica",
        "pantalla tactil",
        "camara trasera",
        "control de crucero adaptativo",
        ],
        enVenta: true,
        propietario: {
        nombre: "Chris",
        edad: 33,
        localizacion: "Dallas",
        },
    },
    'coche 9': {
        marca: "Volvo",
        modelo: "XC90",
        anio: 2020,
        color: "marron",
        precio: 60000,
        carateristicas: [
        "all-wheel drive",
        "asientos de piel",
        "panoramic techo corredizo",
        "suspension adaptativa",
        ],
        enVenta: false,
        propietario: {
        nombre: "Sarah",
        edad: 38,
        localizacion: "Miami",
        },
    },
    'coche 10': {
        marca: "Mitsubishi",
        modelo: "Outlander",
        anio: 2019,
        color: "verde",
        precio: 35000,
        carateristicas: [
        "transmision automatica",
        "pantalla tactil",
        "camara trasera",
        "control de crucero adaptativo",
        ],
        enVenta: true,
        propietario: {
        nombre: "Jason",
        edad: 30,
        localizacion: "Atlanta",
        },
    },
    'coche 11': {
        marca: "Nissan",
        modelo: "Leaf",
        anio: 2021,
        color: "morado",
        precio: 45000,
        carateristicas: [
        "motor electrico",
        "conduccion autonoma",
        "control de crucero adaptativo",
        "pantalla tactil",
        ],
        enVenta: true,
        propietario: {
        nombre: "Katie",
        edad: 26,
        localizacion: "Philadelphia",
        },
    },
    'coche 12': {
        marca: "Toyota",
        modelo: "Rav4",
        anio: 2022,
        color: "rosa",
        precio: 30000,
        carateristicas: [
        "transmision automatica",
        "pantalla tactil",
        "camara trasera",
        "monitoreo de punto ciego",
        ],
        enVenta: false,
        propietario: {
        nombre: "Matt",
        edad: 29,
        localizacion: "Phoenix",
        },
    },
    'coche 13': {
        marca: "Honda",
        modelo: "Accord",
        anio: 2020,
        color: "rojo",
        precio: 30000,
        carateristicas: [
        "transmision automatica",
        "pantalla tactil",
        "camara trasera",
        "control de crucero adaptativo",
        ],
        enVenta: true,
        propietario: {
        nombre: "Jasmine",
        edad: 32,
        localizacion: "San Diego",
        },
    },
    'coche 14': {
        marca: "Ford",
        modelo: "Escape",
        anio: 2021,
        color: "negro",
        precio: 35000,
        carateristicas: [
        "transmision automatica",
        "pantalla tactil",
        "camara trasera",
        "control de crucero adaptativo",
        ],
        enVenta: false,
        propietario: {
        nombre: "Ryan",
        edad: 29,
        localizacion: "Denver",
        },
    },
    'coche 15': {
        marca: "Honda",
        modelo: "CR-V",
        anio: 2018,
        color: "plata",
        precio: 30000,
        carateristicas: [
        "transmision automatica",
        "pantalla tactil",
        "camara trasera",
        "control de crucero adaptativo",
        ],
        enVenta: true,
        propietario: {
        nombre: "Megan",
        edad: 27,
        localizacion: "Detroit",
        },
    },
    'coche 16': {
        marca: "Nissan",
        modelo: "Rogue",
        anio: 2020,
        color: "azul",
        precio: 30000,
        carateristicas: [
        "transmision automatica",
        "pantalla tactil",
        "camara trasera",
        "control de crucero adaptativo",
        ],
        enVenta: true,
        propietario: {
        nombre: "Ben",
        edad: 35,
        localizacion: "Minneapolis",
        },
    }
};